# https://pypi.org/project/yaml-rs
#
# yaml_rs-<version>-cp313-cp313-pyemscripten_2025_0_wasm32.whl
# yaml_rs-<version>-cp314-cp314-pyemscripten_2026_0_wasm32.whl
yaml_rs_version = "0.1.6"

# https://github.com/pyodide/pyodide
pyodide_version = "314.0.2"
